#!/bin/bash

# Authors: see AUTHORS.md at project root.
# CopyPolicy: released under the terms of the LGPLv2.1, see LICENSE at project root.
# URL: https://github.com/roboticslab-uc3m/amor-configuration-files

# Dependencies:
# - https://github.com/roboticslab-uc3m/amor-openrave-models  (provides amor.robot.xml)
# - https://github.com/roboticslab-uc3m/openrave-yarp-plugins  (provides OpenraveYarpPluginLoader)

openrave /usr/local/share/amor/contexts/openrave/models/amor.robot.xml --module OpenraveYarpPluginLoader "open --device controlBoard_nws_yarp --subdevice YarpOpenraveControlboard --robotIndex 0 --allManipulators"
